version: "3.9"
services:
  backend:
    build: ./app
    container_name: movie-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - ./app/data:/app/data
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  frontend:
    build: ./frontend
    container_name: movie-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
